package com.trilogys.quotapulse.core

import org.json.JSONObject
import kotlin.math.max

internal object ProviderParsers {
    fun codex(accountId:String,body:String,nowEpoch:Long=System.currentTimeMillis()/1000):UsageSnapshot{val rate=JSONObject(body).optJSONObject("rate_limit")?:error("Missing rate_limit");val windows=buildList{val keys=rate.keys();while(keys.hasNext()){val key=keys.next();if(!key.endsWith("_window"))continue;val raw=rate.optJSONObject(key)?:continue;if(!raw.has("used_percent"))continue;val duration=raw.optLong("limit_window_seconds",0);val reset=when{raw.optLong("reset_at",0)>0->raw.optLong("reset_at");raw.optLong("reset_after_seconds",-1)>=0->nowEpoch+raw.optLong("reset_after_seconds");else->null};add(UsageWindow("codex-$key",durationLabel(duration),100-raw.optDouble("used_percent"),reset))}}.distinctBy{it.label};if(windows.isEmpty())error("No Codex quota windows");return UsageSnapshot(accountId,ProviderId.CODEX,windows=windows)}
    fun claude(accountId:String,body:String):UsageSnapshot{val root=JSONObject(body);val windows=buildList{root.optJSONObject("five_hour")?.let{add(UsageWindow("claude-5h","5h",100-it.optDouble("utilization"),parseIsoEpoch(it.optString("resets_at"))))};root.optJSONObject("seven_day")?.let{add(UsageWindow("claude-week","周",100-it.optDouble("utilization"),parseIsoEpoch(it.optString("resets_at"))))}};if(windows.isEmpty())error("No Claude quota windows");return UsageSnapshot(accountId,ProviderId.CLAUDE,windows=windows)}
    fun kimi(accountId:String,body:String,nowEpoch:Long=System.currentTimeMillis()/1000):UsageSnapshot{val root=JSONObject(body);val windows=mutableListOf<UsageWindow>();root.optJSONArray("limits")?.let{limits->for(i in 0 until limits.length()){val e=limits.optJSONObject(i)?:continue;parseKimiDetail(e.optJSONObject("detail")?:e,kimiDurationSeconds(e.optJSONObject("window")?:e),"kimi-$i",nowEpoch)?.let(windows::add)}};root.optJSONObject("usage")?.let{if(windows.none{w->w.label=="周"})parseKimiDetail(it,604800,"kimi-week-summary",nowEpoch)?.let(windows::add)};val distinct=windows.distinctBy{it.label};if(distinct.isEmpty())error("No Kimi quota windows");return UsageSnapshot(accountId,ProviderId.KIMI,windows=distinct)}
    fun deepSeek(accountId:String,body:String):UsageSnapshot{val root=JSONObject(body);val infos=root.optJSONArray("balance_infos")?:error("No balance_infos");var selected:JSONObject?=null;for(currency in listOf("CNY","USD")){for(i in 0 until infos.length()){val x=infos.optJSONObject(i)?:continue;if(x.optString("currency")==currency){selected=x;break}};if(selected!=null)break};if(selected==null&&infos.length()>0)selected=infos.optJSONObject(0);val info=selected?:error("Unknown balance format");val currency=info.optString("currency");val symbol=when(currency){"CNY"->"¥";"USD"->"$";else->"$currency "};return UsageSnapshot(accountId,ProviderId.DEEPSEEK,balance=BalanceSnapshot(currency,symbol,info.optDouble("total_balance"),info.optDouble("granted_balance"),info.optDouble("topped_up_balance"),root.optBoolean("is_available",true)))}
    fun miniMax(accountId:String,body:String):UsageSnapshot{val root=JSONObject(body);val data=root.optJSONObject("data")?:root;val current=number(data,"currentUsage","current_usage","used");val total=number(data,"totalUsage","total_usage","limit");val windows=if(current!=null&&total!=null&&total>0)listOf(UsageWindow("minimax-plan","计划",((total-current)/total*100).coerceIn(0.0,100.0)))else emptyList();return UsageSnapshot(accountId,ProviderId.MINIMAX,windows=windows)}
    fun glm(accountId:String,body:String):UsageSnapshot{val root=JSONObject(body);val data=root.optJSONObject("data")?:root.optJSONObject("result")?:root;val percent=number(data,"remainingPercent","remaining_percent","percentage");if(percent!=null)return UsageSnapshot(accountId,ProviderId.GLM,windows=listOf(UsageWindow("glm-plan","计划",percent.coerceIn(0.0,100.0))));val total=number(data,"total","limit","quota","totalQuota","total_quota");val used=number(data,"used","usage","usedQuota","used_quota");if(total!=null&&used!=null&&total>0)return UsageSnapshot(accountId,ProviderId.GLM,windows=listOf(UsageWindow("glm-plan","计划",((total-used)/total*100).coerceIn(0.0,100.0))));return UsageSnapshot(accountId,ProviderId.GLM)}
    fun copilot(accountId:String,body:String):UsageSnapshot{val root=JSONObject(body);val quota=root.optJSONObject("quota_snapshots")?:root;val windows=mutableListOf<UsageWindow>();val keys=quota.keys();while(keys.hasNext()){val key=keys.next();val value=quota.optJSONObject(key)?:continue;val remaining=when{value.has("percent_remaining")->value.optDouble("percent_remaining");value.has("remaining")&&value.has("entitlement")&&value.optDouble("entitlement")>0->value.optDouble("remaining")/value.optDouble("entitlement")*100;else->continue};windows+=UsageWindow("copilot-$key",key.replace('_',' '),remaining.coerceIn(0.0,100.0),parseFlexibleEpoch(value.opt("reset_date")))};return UsageSnapshot(accountId,ProviderId.COPILOT,windows=windows)}
    private fun number(o:JSONObject,vararg keys:String):Double?{for(k in keys)if(o.has(k)&&!o.isNull(k)){val v=o.opt(k);when(v){is Number->return v.toDouble();is String->v.toDoubleOrNull()?.let{return it}}};return null}
    private fun durationLabel(s:Long)=when{s in 1..21600->"${max(1,s/3600)}h";s in 21601..691200->if(s>=518400)"周" else "${max(1,s/86400)}d";else->"额度"}
    private fun kimiDurationSeconds(w:JSONObject):Long{val d=w.optLong("duration",0);val u=w.optString("timeUnit",w.optString("time_unit")).uppercase().removePrefix("TIME_UNIT_");return when{u.startsWith("SECOND")->d;u.startsWith("MINUTE")->d*60;u.startsWith("HOUR")->d*3600;u.startsWith("DAY")->d*86400;else->0}}
    private fun parseKimiDetail(d:JSONObject,duration:Long,id:String,now:Long):UsageWindow?{val limit=d.optDouble("limit",0.0);if(limit<=0)return null;val used=if(d.has("used"))d.optDouble("used") else limit-d.optDouble("remaining",limit);val reset=listOf("resetAt","reset_at","resetTime","reset_time").firstNotNullOfOrNull{parseFlexibleEpoch(d.opt(it))}?:listOf("resetIn","reset_in","ttl").firstNotNullOfOrNull{k->d.optLong(k,-1).takeIf{it>=0}?.let{now+it}};return UsageWindow(id,durationLabel(duration),((limit-used)/limit*100).coerceIn(0.0,100.0),reset)}
    private fun parseFlexibleEpoch(v:Any?):Long?=when(v){is Number->v.toLong().let{if(it>10000000000L)it/1000 else it};is String->parseIsoEpoch(v);else->null}
    private fun parseIsoEpoch(v:String):Long?=try{java.time.Instant.parse(v).epochSecond}catch(_:Exception){null}
}
