package com.trilogys.aiquota.core

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

class AccountStore(context: Context) {
    private val prefs = context.getSharedPreferences("aiquota_state", Context.MODE_PRIVATE)
    fun accounts(): List<AccountRecord> { val array = JSONArray(prefs.getString("accounts", "[]") ?: "[]"); return buildList { for (i in 0 until array.length()) { val o = array.optJSONObject(i) ?: continue; runCatching { add(AccountRecord(id=o.getString("id"), provider=ProviderId.valueOf(o.getString("provider")), name=o.optString("name",o.getString("provider")), enabled=o.optBoolean("enabled",true), order=o.optInt("order",i), providerAccountId=o.stringOrNull("providerAccountId"), createdAtEpochSeconds=o.optLong("createdAt",System.currentTimeMillis()/1000))) } } }.sortedWith(compareBy<AccountRecord>{it.order}.thenBy{it.name}) }
    fun upsert(account: AccountRecord) { val items=accounts().toMutableList(); val index=items.indexOfFirst{it.id==account.id}; if(index>=0) items[index]=account else items+=account.copy(order=(items.maxOfOrNull{it.order}?:-1)+1); saveAccounts(normalizeOrder(items)) }
    fun replaceAccounts(items:List<AccountRecord>){saveAccounts(normalizeOrder(items.sortedBy{it.order}))}
    fun setEnabled(accountId:String,enabled:Boolean){saveAccounts(normalizeOrder(accounts().map{if(it.id==accountId)it.copy(enabled=enabled)else it}))}
    fun move(accountId:String,delta:Int){if(delta==0)return;val items=normalizeOrder(accounts()).toMutableList();val from=items.indexOfFirst{it.id==accountId};if(from<0)return;val to=(from+delta).coerceIn(0,items.lastIndex);if(from==to)return;val item=items.removeAt(from);items.add(to,item);saveAccounts(normalizeOrder(items))}
    fun delete(accountId:String){saveAccounts(normalizeOrder(accounts().filterNot{it.id==accountId}));prefs.edit().remove("snapshot.$accountId").remove("cooldown.$accountId").apply()}
    fun saveSnapshot(snapshot:UsageSnapshot){val o=JSONObject().put("accountId",snapshot.accountId).put("provider",snapshot.provider.name).put("updatedAt",snapshot.updatedAtEpochSeconds).put("stale",snapshot.stale).put("error",snapshot.errorMessage).put("errorKind",snapshot.errorKind?.name);val windows=JSONArray();snapshot.windows.forEach{w->windows.put(JSONObject().put("id",w.id).put("label",w.label).put("remaining",w.remainingPercent).put("resetAt",w.resetAtEpochSeconds))};o.put("windows",windows);snapshot.balance?.let{b->o.put("balance",JSONObject().put("currency",b.currency).put("symbol",b.symbol).put("total",b.total).put("granted",b.granted).put("toppedUp",b.toppedUp).put("available",b.available))};prefs.edit().putString("snapshot.${snapshot.accountId}",o.toString()).apply()}
    fun snapshot(accountId:String):UsageSnapshot?{val raw=prefs.getString("snapshot.$accountId",null)?:return null;return runCatching{val o=JSONObject(raw);val wa=o.optJSONArray("windows")?:JSONArray();val windows=buildList{for(i in 0 until wa.length()){val w=wa.getJSONObject(i);add(UsageWindow(w.getString("id"),w.getString("label"),w.getDouble("remaining"),w.optLong("resetAt").takeIf{it>0}))}};val balance=o.optJSONObject("balance")?.let{b->BalanceSnapshot(b.optString("currency"),b.optString("symbol"),b.optDouble("total"),b.optDouble("granted"),b.optDouble("toppedUp"),b.optBoolean("available",true))};val error=o.optString("error").takeIf{it.isNotBlank()&&it!="null"};val kind=o.optString("errorKind").takeIf{it.isNotBlank()&&it!="null"}?.let{runCatching{ProviderErrorKind.valueOf(it)}.getOrNull()}?:if(error!=null)ProviderErrorClassifier.classify(error)else null;UsageSnapshot(accountId,ProviderId.valueOf(o.getString("provider")),windows,balance,o.optLong("updatedAt"),o.optBoolean("stale"),error,kind)}.getOrNull()}
    fun markStale(accountId:String,error:String,kind:ProviderErrorKind?=null){val old=snapshot(accountId)?:return;saveSnapshot(old.copy(stale=true,errorMessage=error,errorKind=kind?:ProviderErrorClassifier.classify(error)))}
    fun setCooldown(accountId:String,untilEpochSeconds:Long){prefs.edit().putLong("cooldown.$accountId",untilEpochSeconds).apply()}
    fun cooldownUntil(accountId:String):Long?=prefs.getLong("cooldown.$accountId",0).takeIf{it>System.currentTimeMillis()/1000}
    fun clearCooldown(accountId:String){prefs.edit().remove("cooldown.$accountId").apply()}
    private fun normalizeOrder(items:List<AccountRecord>):List<AccountRecord> = items.mapIndexed{index,account->account.copy(order=index)}
    private fun saveAccounts(items:List<AccountRecord>){val array=JSONArray();items.forEach{a->array.put(JSONObject().put("id",a.id).put("provider",a.provider.name).put("name",a.name).put("enabled",a.enabled).put("order",a.order).putNullable("providerAccountId",a.providerAccountId).put("createdAt",a.createdAtEpochSeconds))};prefs.edit().putString("accounts",array.toString()).apply()}
    private fun JSONObject.putNullable(key:String,value:Any?):JSONObject=put(key,value ?: JSONObject.NULL)
    private fun JSONObject.stringOrNull(key:String):String?=if(!has(key)||isNull(key))null else optString(key).takeIf{it.isNotBlank()}
}
