package com.trilogys.aiquota.core

import okhttp3.FormBody
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import java.io.IOException

class UsageService(private val credentialStore:CredentialStore,private val client:OkHttpClient=OkHttpClient()) {
    fun refresh(account:AccountRecord):UsageSnapshot { val credential=credentialStore.get(account.id)?:error("Missing credential");return when(account.provider){ProviderId.CODEX->fetchCodex(account,credential);ProviderId.CLAUDE->fetchClaude(account,credential);ProviderId.KIMI->fetchKimi(account,credential);ProviderId.DEEPSEEK->fetchDeepSeek(account,credential);ProviderId.MINIMAX->fetchMiniMax(account,credential);ProviderId.GLM->fetchGLM(account,credential);ProviderId.COPILOT->fetchCopilot(account,credential)} }
    private fun execute(request:Request):Pair<Int,String> = client.newCall(request).execute().use{it.code to it.body?.string().orEmpty()}
    private fun fetchCodex(account:AccountRecord,initial:Credential):UsageSnapshot{if(initial.authenticationMode==CredentialAuthenticationMode.API_KEY)return fetchOpenAIKey(account,initial);var c=initial;fun call(x:Credential):Pair<Int,String>{val b=Request.Builder().url("https://chatgpt.com/backend-api/wham/usage").header("Authorization","Bearer ${x.accessToken}").header("User-Agent","codex-cli").header("Accept","application/json");x.accountId?.takeIf(String::isNotBlank)?.let{b.header("chatgpt-account-id",it)};return execute(b.build())};var (code,body)=call(c);if(code==401&&!c.refreshToken.isNullOrBlank()){c=refreshCodex(account.id,c);val r=call(c);code=r.first;body=r.second};if(code !in 200..299)throw IOException("Codex HTTP $code: $body");return ProviderParsers.codex(account.id,body)}
    private fun fetchOpenAIKey(a:AccountRecord,c:Credential):UsageSnapshot{val base=apiV1BaseUrl(c.baseUrl,"https://api.openai.com");val(code,body)=execute(Request.Builder().url("$base/models").header("Authorization","Bearer ${c.accessToken}").header("Accept","application/json").build());if(code !in 200..299)throw IOException("OpenAI HTTP $code: $body");val count=JSONObject(body).optJSONArray("data")?.length()?:0;return UsageSnapshot(a.id,ProviderId.CODEX,connectionLabel="API Key · $count models")}
    private fun refreshCodex(id:String,c:Credential):Credential{val refresh=c.refreshToken?:error("Missing refresh token");val form=FormBody.Builder().add("grant_type","refresh_token").add("refresh_token",refresh).add("client_id",c.clientId?:CODEX_CLIENT_ID).build();val (code,body)=execute(Request.Builder().url("https://auth.openai.com/oauth/token").post(form).header("Accept","application/json").build());if(code !in 200..299)throw IOException("Codex refresh HTTP $code: $body");val j=JSONObject(body);val u=c.copy(accessToken=j.getString("access_token"),refreshToken=j.optString("refresh_token").takeIf{it.isNotBlank()}?:refresh,idToken=j.optString("id_token").takeIf{it.isNotBlank()}?:c.idToken);credentialStore.save(id,u);return u}
    private fun fetchClaude(account:AccountRecord,initial:Credential):UsageSnapshot{if(initial.authenticationMode==CredentialAuthenticationMode.API_KEY)return fetchClaudeKey(account,initial);var c=initial;if((c.expiresAtEpochSeconds?:Long.MAX_VALUE)-nowEpoch()<60&&!c.refreshToken.isNullOrBlank())c=refreshClaude(account.id,c);fun call(x:Credential):Pair<Int,String>{return execute(Request.Builder().url("https://api.anthropic.com/api/oauth/usage").header("Authorization","Bearer ${x.accessToken}").header("anthropic-beta","oauth-2025-04-20").header("User-Agent","claude-cli").header("Accept","application/json").build())};var (code,body)=call(c);if(code==401&&!c.refreshToken.isNullOrBlank()){c=refreshClaude(account.id,c);val r=call(c);code=r.first;body=r.second};if(code !in 200..299)throw IOException("Claude HTTP $code: $body");return ProviderParsers.claude(account.id,body)}
    private fun fetchClaudeKey(a:AccountRecord,c:Credential):UsageSnapshot{val base=apiV1BaseUrl(c.baseUrl,"https://api.anthropic.com");val(code,body)=execute(Request.Builder().url("$base/models").header("x-api-key",c.accessToken).header("anthropic-version","2023-06-01").header("Accept","application/json").build());if(code !in 200..299)throw IOException("Claude API HTTP $code: $body");val count=JSONObject(body).optJSONArray("data")?.length()?:0;return UsageSnapshot(a.id,ProviderId.CLAUDE,connectionLabel="API Key · $count models")}
    private fun refreshClaude(id:String,c:Credential):Credential{val refresh=c.refreshToken?:error("Missing refresh token");val payload=JSONObject().put("grant_type","refresh_token").put("refresh_token",refresh).put("client_id",c.clientId?:CLAUDE_CLIENT_ID).toString().toRequestBody("application/json".toMediaType());val (code,body)=execute(Request.Builder().url("https://platform.claude.com/v1/oauth/token").post(payload).header("Accept","application/json").build());if(code !in 200..299)throw IOException("Claude refresh HTTP $code: $body");val j=JSONObject(body);val u=c.copy(accessToken=j.getString("access_token"),refreshToken=j.optString("refresh_token").takeIf{it.isNotBlank()}?:refresh,expiresAtEpochSeconds=j.optLong("expires_in").takeIf{it>0}?.let{nowEpoch()+it});credentialStore.save(id,u);return u}
    private fun fetchKimi(account:AccountRecord,initial:Credential):UsageSnapshot{if(initial.authenticationMode==CredentialAuthenticationMode.API_KEY)return fetchKimiKey(account,initial);var c=initial;if((c.expiresAtEpochSeconds?:Long.MAX_VALUE)-nowEpoch()<60&&!c.refreshToken.isNullOrBlank())c=refreshKimi(account.id,c);fun call(x:Credential):Pair<Int,String>{val b=Request.Builder().url("https://api.kimi.com/coding/v1/usages").header("Authorization","Bearer ${x.accessToken}").header("Accept","application/json");x.deviceHeaders?.forEach{(k,v)->b.header(k,v)};return execute(b.build())};var (code,body)=call(c);if(code in listOf(401,403)&&!c.refreshToken.isNullOrBlank()){c=refreshKimi(account.id,c);val r=call(c);code=r.first;body=r.second};if(code !in 200..299)throw IOException("Kimi HTTP $code: $body");return ProviderParsers.kimi(account.id,body)}
    private fun fetchKimiKey(a:AccountRecord,c:Credential):UsageSnapshot{val base=apiV1BaseUrl(c.baseUrl,"https://api.moonshot.cn");val(code,body)=execute(Request.Builder().url("$base/models").header("Authorization","Bearer ${c.accessToken}").header("Accept","application/json").build());if(code !in 200..299)throw IOException("Kimi API HTTP $code: $body");val data=JSONObject(body).optJSONArray("data");val models=buildList{if(data!=null)for(i in 0 until data.length())data.optJSONObject(i)?.optString("id")?.takeIf(String::isNotBlank)?.let(::add)}.sorted();val(balanceCode,balanceBody)=execute(Request.Builder().url("$base/users/me/balance").header("Authorization","Bearer ${c.accessToken}").header("Accept","application/json").build());val balance=if(balanceCode in 200..299)JSONObject(balanceBody).optJSONObject("data")?.let{d->BalanceSnapshot("CNY","¥",d.optDouble("available_balance"),d.optDouble("voucher_balance"),d.optDouble("cash_balance"),true)}else null;return UsageSnapshot(a.id,ProviderId.KIMI,balance=balance,connectionLabel="API Key · ${models.size} models",availableModels=models)}
    private fun refreshKimi(id:String,c:Credential):Credential{val refresh=c.refreshToken?:error("Missing refresh token");val form=FormBody.Builder().add("client_id",c.clientId?:KIMI_CLIENT_ID).add("grant_type","refresh_token").add("refresh_token",refresh).build();val b=Request.Builder().url("https://auth.kimi.com/api/oauth/token").post(form).header("Accept","application/json");c.deviceHeaders?.forEach{(k,v)->b.header(k,v)};val (code,body)=execute(b.build());if(code !in 200..299)throw IOException("Kimi refresh HTTP $code: $body");val j=JSONObject(body);val u=c.copy(accessToken=j.getString("access_token"),refreshToken=j.optString("refresh_token").takeIf{it.isNotBlank()}?:refresh,expiresAtEpochSeconds=j.optLong("expires_in").takeIf{it>0}?.let{nowEpoch()+it});credentialStore.save(id,u);return u}
    private fun fetchDeepSeek(a:AccountRecord,c:Credential):UsageSnapshot{val base=normalizedBaseUrl(c.baseUrl,"https://api.deepseek.com");val (code,body)=execute(Request.Builder().url("$base/user/balance").header("Authorization","Bearer ${c.accessToken}").header("Accept","application/json").build());if(code !in 200..299)throw IOException("DeepSeek HTTP $code: $body");return ProviderParsers.deepSeek(a.id,body)}
    private fun fetchMiniMax(a:AccountRecord,c:Credential):UsageSnapshot{val base=normalizedBaseUrl(c.baseUrl,"https://api.minimax.io");val (code,body)=execute(Request.Builder().url("$base/v1/api/openplatform/coding_plan/remains").header("Authorization","Bearer ${c.accessToken}").header("Accept","application/json").header("Content-Type","application/json").build());if(code !in 200..299)throw IOException("MiniMax HTTP $code: $body");return ProviderParsers.miniMax(a.id,body)}
    private fun fetchGLM(a:AccountRecord,c:Credential):UsageSnapshot{val base=normalizedBaseUrl(c.baseUrl,"https://open.bigmodel.cn");var failure="";for(url in listOf("$base/api/monitor/usage/quota/limit","$base/api/paas/v4/usage/quota")){val (code,body)=execute(Request.Builder().url(url).header("Authorization","Bearer ${c.accessToken}").header("Accept","application/json").build());if(code in 200..299)return ProviderParsers.glm(a.id,body);failure="HTTP $code"};throw IOException("GLM quota unavailable: $failure")}
    private fun fetchCopilot(a:AccountRecord,c:Credential):UsageSnapshot{val base=normalizedBaseUrl(c.baseUrl,"https://api.github.com");val (code,body)=execute(Request.Builder().url("$base/copilot_internal/user").header("Authorization","token ${c.accessToken}").header("Accept","application/json").header("User-Agent","AIQuotaNative").build());if(code !in 200..299)throw IOException("Copilot HTTP $code: $body");return ProviderParsers.copilot(a.id,body)}
    private fun normalizedBaseUrl(value:String?,fallback:String)=value?.trim()?.trimEnd('/')?.takeIf{it.startsWith("https://")||it.startsWith("http://")}?:fallback
    private fun apiV1BaseUrl(value:String?,fallback:String):String{val base=normalizedBaseUrl(value,fallback);return if(base.endsWith("/v1",true))base else "$base/v1"}
    private fun nowEpoch()=System.currentTimeMillis()/1000
    companion object{const val CODEX_CLIENT_ID="app_EMoamEEZ73f0CkXaXp7hrann";const val CLAUDE_CLIENT_ID="9d1c250a-e61b-44d9-88ed-5944d1962f5e";const val KIMI_CLIENT_ID="17e5f671-d194-4dfb-9706-5516cb48c098"}
}
