#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/SigningConfig.xcconfig"
TEAM=""
BUNDLE=""
WIDGET_BUNDLE=""
APP_GROUP=""
KEYCHAIN_SUFFIX=""
STYLE="Automatic"
APP_PROFILE=""
WIDGET_PROFILE=""

usage() {
  cat <<'USAGE'
Usage:
  ./Scripts/configure_signing.sh --team TEAMID --bundle com.yourname.aiquota [options]

Options:
  --team TEAMID                  Apple Developer Team ID
  --bundle BUNDLE_ID             Main app bundle id
  --widget-bundle BUNDLE_ID      Widget bundle id (default <bundle>.widget)
  --app-group GROUP_ID           Shared App Group (default group.<bundle>.shared)
  --keychain-suffix GROUP        Keychain group without team prefix (default <bundle>.shared)
  --style Automatic|Manual       Signing style (default Automatic)
  --app-profile NAME             Main app provisioning profile specifier (Manual)
  --widget-profile NAME          Widget provisioning profile specifier (Manual)

For existing purchased/manual profiles, use the exact identifiers authorized by those profiles.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --team) TEAM="${2:-}"; shift 2 ;;
    --bundle) BUNDLE="${2:-}"; shift 2 ;;
    --widget-bundle) WIDGET_BUNDLE="${2:-}"; shift 2 ;;
    --app-group) APP_GROUP="${2:-}"; shift 2 ;;
    --keychain-suffix) KEYCHAIN_SUFFIX="${2:-}"; shift 2 ;;
    --style) STYLE="${2:-}"; shift 2 ;;
    --app-profile) APP_PROFILE="${2:-}"; shift 2 ;;
    --widget-profile) WIDGET_PROFILE="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

[[ -n "$TEAM" ]] || { echo "--team is required" >&2; exit 2; }
[[ -n "$BUNDLE" ]] || { echo "--bundle is required" >&2; exit 2; }
[[ "$STYLE" == "Automatic" || "$STYLE" == "Manual" ]] || { echo "--style must be Automatic or Manual" >&2; exit 2; }
if [[ "$STYLE" == "Manual" ]]; then
  [[ -n "$APP_PROFILE" ]] || { echo "Manual signing requires --app-profile" >&2; exit 2; }
  [[ -n "$WIDGET_PROFILE" ]] || { echo "Manual signing requires --widget-profile" >&2; exit 2; }
fi

WIDGET_BUNDLE="${WIDGET_BUNDLE:-$BUNDLE.widget}"
APP_GROUP="${APP_GROUP:-group.$BUNDLE.shared}"
KEYCHAIN_SUFFIX="${KEYCHAIN_SUFFIX:-$BUNDLE.shared}"

cat > "$OUT" <<CFG
// Generated by Scripts/configure_signing.sh
AIQUOTA_TEAM_ID = $TEAM
AIQUOTA_CODE_SIGN_STYLE = $STYLE
AIQUOTA_APP_PROFILE_SPECIFIER = $APP_PROFILE
AIQUOTA_WIDGET_PROFILE_SPECIFIER = $WIDGET_PROFILE

AIQUOTA_APP_BUNDLE_ID = $BUNDLE
AIQUOTA_WIDGET_BUNDLE_ID = $WIDGET_BUNDLE
AIQUOTA_APP_GROUP = $APP_GROUP
AIQUOTA_KEYCHAIN_SUFFIX = $KEYCHAIN_SUFFIX
CFG

chmod 600 "$OUT" 2>/dev/null || true
printf 'Wrote %s\n' "$OUT"
printf 'Main App:  %s\nWidget:    %s\nApp Group: %s\nKeychain:  <AppIdentifierPrefix>%s\n' "$BUNDLE" "$WIDGET_BUNDLE" "$APP_GROUP" "$KEYCHAIN_SUFFIX"
