#!/usr/bin/env bash
set -euo pipefail

[[ $# -eq 2 ]] || { echo "Usage: $0 App.mobileprovision Widget.mobileprovision" >&2; exit 2; }
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/SigningConfig.xcconfig"
command -v security >/dev/null 2>&1 || { echo "macOS security tool required." >&2; exit 1; }

TMP="$(mktemp -d -t quotapulse-derive)"
trap 'rm -rf "$TMP"' EXIT
security cms -D -i "$1" > "$TMP/app.plist"
security cms -D -i "$2" > "$TMP/widget.plist"

python3 - "$TMP/app.plist" "$TMP/widget.plist" "$OUT" <<'PY'
import plistlib, sys, datetime
app_path, widget_path, out_path = sys.argv[1:]

def load(p):
    with open(p,'rb') as f: return plistlib.load(f)
app, widget = load(app_path), load(widget_path)

def ent(p): return p.get('Entitlements') or {}
def first(seq): return seq[0] if seq else None

def profile_prefix(p):
    v = first(p.get('ApplicationIdentifierPrefix') or [])
    if v: return v.rstrip('.')
    aid = ent(p).get('application-identifier') or ent(p).get('com.apple.application-identifier')
    return aid.split('.',1)[0] if aid and '.' in aid else None

def bundle_id(p):
    e=ent(p)
    aid=e.get('application-identifier') or e.get('com.apple.application-identifier')
    pref=profile_prefix(p)
    if not aid or not pref or not aid.startswith(pref+'.'):
        return None
    suffix=aid[len(pref)+1:]
    if '*' in suffix:
        return None
    return suffix

def validate_exp(label,p):
    exp=p.get('ExpirationDate')
    if exp and exp.replace(tzinfo=None) <= datetime.datetime.utcnow():
        raise SystemExit(f'{label} provisioning profile expired at {exp}')

validate_exp('App',app); validate_exp('Widget',widget)
app_teams=set(app.get('TeamIdentifier') or [])
widget_teams=set(widget.get('TeamIdentifier') or [])
teams=app_teams & widget_teams
if len(teams)!=1:
    raise SystemExit(f'Profiles must share exactly one Team ID; app={sorted(app_teams)}, widget={sorted(widget_teams)}')
team=next(iter(teams))
app_prefix, widget_prefix=profile_prefix(app), profile_prefix(widget)
if not app_prefix or app_prefix != widget_prefix:
    raise SystemExit(f'Profiles must share the same AppIdentifierPrefix; app={app_prefix}, widget={widget_prefix}')
prefix=app_prefix
app_bundle, widget_bundle=bundle_id(app), bundle_id(widget)
if not app_bundle or not widget_bundle:
    raise SystemExit('Cannot infer exact Bundle IDs from wildcard profiles. Use explicit App IDs/profiles.')

app_groups=set(ent(app).get('com.apple.security.application-groups') or [])
widget_groups=set(ent(widget).get('com.apple.security.application-groups') or [])
common_groups=sorted(app_groups & widget_groups)
if not common_groups:
    raise SystemExit(f'No shared App Group. app={sorted(app_groups)}, widget={sorted(widget_groups)}')
app_group=common_groups[0]

def allowed(pattern, desired):
    if pattern == desired: return True
    if pattern.endswith('*') and desired.startswith(pattern[:-1]): return True
    return False
app_kg=ent(app).get('keychain-access-groups') or []
widget_kg=ent(widget).get('keychain-access-groups') or []
candidates=[]
for g in app_kg + widget_kg:
    if '*' not in g and g.startswith(prefix+'.') and g not in candidates:
        candidates.append(g)
def both_allow(g): return any(allowed(x,g) for x in app_kg) and any(allowed(x,g) for x in widget_kg)
shared=next((g for g in candidates if both_allow(g)), None)
if not shared:
    candidate=f'{prefix}.{app_bundle}.shared'
    if both_allow(candidate): shared=candidate
if not shared:
    raise SystemExit(f'No compatible shared Keychain group. app={app_kg}, widget={widget_kg}')
key_suffix=shared[len(prefix)+1:] if shared.startswith(prefix+'.') else None
if not key_suffix:
    raise SystemExit(f'Unsupported Keychain group prefix: {shared}')

app_name=app.get('Name') or ''
widget_name=widget.get('Name') or ''
text=f'''// Generated by Scripts/derive_signing_config.sh\nQUOTAPULSE_TEAM_ID = {team}\nQUOTAPULSE_CODE_SIGN_STYLE = Manual\nQUOTAPULSE_APP_PROFILE_SPECIFIER = {app_name}\nQUOTAPULSE_WIDGET_PROFILE_SPECIFIER = {widget_name}\n\nQUOTAPULSE_APP_BUNDLE_ID = {app_bundle}\nQUOTAPULSE_WIDGET_BUNDLE_ID = {widget_bundle}\nQUOTAPULSE_APP_GROUP = {app_group}\nQUOTAPULSE_KEYCHAIN_SUFFIX = {key_suffix}\n'''
open(out_path,'w').write(text)
print(f'Team ID:       {team}')
print(f'App prefix:    {prefix}')
print(f'App bundle:    {app_bundle}')
print(f'Widget bundle: {widget_bundle}')
print(f'App Group:     {app_group}')
print(f'Keychain:      {shared}')
print(f'App profile:   {app_name}')
print(f'Widget profile:{widget_name}')
print(f'Wrote {out_path}')
PY
chmod 600 "$OUT" 2>/dev/null || true
